# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{convenient_scopes}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ivan Schneider"]
  s.date = %q{2011-07-16}
  s.description = %q{Dynamic scopes by convention for ActiveRecord 3}
  s.email = %q{isc@massivebraingames.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "convenient_scopes.gemspec",
    "lib/convenient_scopes.rb",
    "test/helper.rb",
    "test/test_all_and_any_conditions.rb",
    "test/test_associations.rb",
    "test/test_conditions.rb",
    "test/test_ordering.rb",
    "test/test_search_with_hash.rb"
  ]
  s.homepage = %q{http://github.com/isc/convenient_scopes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Dynamic scopes by convention for ActiveRecord 3}
  s.test_files = [
    "test/helper.rb",
    "test/test_all_and_any_conditions.rb",
    "test/test_associations.rb",
    "test/test_conditions.rb",
    "test/test_ordering.rb",
    "test/test_search_with_hash.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.4"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.4"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.4"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

